### ISSUE TITLE
Question: plugin applicability

### ISSUE THREAD

**Issue by TheOrdinaryWow** [nmn/tw-to-stylex#2]
Is this plugin currently targeting only classNames scoped by `cn()`, or is it available for all classes that includes Tailwind CSS?

**Comment by nmn** [comment]
It works for most classNames. Here's the general approach of what it does:
- Any `className` prop on a native DOM elements, (such as `<div`) is converted into a `{...stylex.props}`
- Any `className` prop on a custom component (if it is using a capital letter), is converted to stylex styles but passed in as the `className` prop.
- Any `tw()` function is converted to a stylex style but otherwise left as is.
  - This means you can define constants within your component that use `tw()` to define styles and then apply them to multiple JSX elements, but you have to use `{...stylex.props}` yourself to apply it.
- `cn()` is used to detect when multiple styles are being "merged". It creates an array of multiple styles. The array is passed to `{...stylex.props(arr)}` or `className={arr}` depending on whether it is being applied to a native DOM element or a custom component as explained in the two lines above.

**Comment by nmn** [comment]
There is one major benefit of using the tw() function. Strong typed.

![image](https://github.com/user-attachments/assets/05ba6346-d7a2-415a-a298-4b4300227dc2)

**Comment by TheOrdinaryWow** [comment]
> There is one major benefit of using the tw() function. Strong typed.
> 
> ![image](https://private-user-images.githubusercontent.com/3582514/393752941-05ba6346-d7a2-415a-a298-4b4300227dc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MzU1MjgsIm5iZiI6MTczMzczNTIyOCwicGF0aCI6Ii8zNTgyNTE0LzM5Mzc1Mjk0MS0wNWJhNjM0Ni1kN2EyLTQxNWEtYTI5OC00YjQzMDAyMjdkYzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDlUMDkwNzA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2QyNjIxYTcxZTI3YTkwMWI2Yzk1MmU5ZmIwYTQ2OTMwYjBjYjA1ZDM3YmJiOWZiZGRmZWU4NDYzY2E4MGYwYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ZQiRt3HtO7UNCiNiMcafUfXe8AATh20QH6Io_EWoLW4)

Got it. Thanks much.
